spring.application.name=space
#server.port=8103

server.port=${SPRING_SERVER_PORT:8103}
server.protocol=${SPRING_SERVER_PROTOCOL:http}
server.baseurl=${SPRING_SERVER_BASEURL:localhost}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.url=jdbc:${SPRING_DATASOURCE_PREFIX:mariadb}://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:3306}/${SPRING_DATASOURCE_SCHEMA:space}
spring.datasource.driver-class-name=${SPRING_DB_DRIVER:org.mariadb.jdbc.Driver}
spring.jpa.properties.hibernate.dialect=${SPRING_DB_DIALECT:org.hibernate.dialect.MariaDBDialect}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
server.error.whitelabel.enabled=false
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=${SPRING_MAX_FILE_SIZE:4MB}
spring.servlet.multipart.max-request-size=${SPRING_MAX_FILE_SIZE:4MB}
spring.http.multipart.max-request-size=${SPRING_MAX_FILE_SIZE:4MB}
spring.mvc.async.request-timeout=1200000
server.servlet.session.timeout=30m
server.tomcat.connection-timeout=1200000
spring.security.user.name=${SPRING_SECURITY_USERNAME:admin}
spring.security.user.password=${SPRING_SECURITY_USERNAME:admin}
debug=${SPRING_DEBUG:false}
cors.test.url=${CORS_TESTING_URL:https://demo.xap3y.space}
spring.enviroment=${SPRING_ENV:dev}

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.thymeleaf.suffix=.xhtml

spring.mail.host=${SPRING_MAIL_HOST:smtp.xap3y.space}
spring.mail.port=${SPRING_MAIL_PORT:465}
spring.mail.username=${SPRING_MAIL_USERNAME:username}
spring.mail.password=${SPRING_MAIL_PASSWORD:password}
spring.mail.protocol=${SPRING_MAIL_PROTOCOL:smtps}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.ssl.enable=${SPRING_MAIL_SMTP_SSL:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_SMTP_STARTTLS_ENABLE:false}
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000