spring.datasource.username=space
spring.datasource.password=test
spring.datasource.url=jdbc:mariadb://internal.2.db.xap3y.eu:3306/space_test

SPRING_DATASOURCE_USERNAME=space
SPRING_DATASOURCE_PASSWORD=test